### ISSUE TITLE
References error during build. 

### ISSUE THREAD

**Issue by demesg** [swedenconnect/swedish-eid-idp#41]
Hi Martin
I have built and installed swedish-eid-opensaml,opensaml-ext,swedish-eid-shibboleth-base from github. But have some trouble building swedish-eid-idp, seems to be shibboleth-base references to 1.6.2-snapshot.
Changeing to 1.6.1 brings me further, but stops with:

> [ERROR] ..eid/swedish-eid-idp/idp/src/main/java/se/e,legnamnden/eid/idp/authn/controller/SimulatedAuthenticationController.java:[54,62] package se.litsec.swedisheid.opensaml.saml2.authentication.psc does not exist
> [ERROR] ..eid/swedish-eid-idp/idp/src/main/java/se/elegnamnden/eid/idp/authn/controller/SimulatedAuthenticationController.java:[55,62] package se.litsec.swedisheid.opensaml.saml2.authentication.psc does not exist

even though I have installed opensaml3-ext (1.3/1.4)in my repo. 
Maybe it is just me doing wrong.
Keep up the good work, it is very much appreciated 
Magnus

**Comment by martin-lindstrom** [comment]
We are currently working with a new version of the IdP that uses Shibboleth 3.4.4. I'll make sure that everything works a.s.a.p.

**Comment by martin-lindstrom** [comment]
@demesg Make a pull from master and try to build now ... The PR https://github.com/swedenconnect/swedish-eid-idp/pull/42 has updated all dependencies to non-snapshot ones.

**Comment by demesg** [comment]
Works great now ! thank you  //Magnus
