### ISSUE TITLE
Certificates in test-credentials expired. 

### ISSUE THREAD

**Issue by demesg** [swedenconnect/swedish-eid-idp#44]
Hi Martin
Just want to mention that the certificates in the test-credentials folder expired 2019-05-25. 
kind regards Magnus

**Comment by martin-lindstrom** [comment]
Yes. But in a SAML federation when they are published to a SAML metadata service they shouldn't be validated anyway. They are only holders of the public keys, so ... You trust the metadata signer's certificate. That's it. Don't validate the certificates in the aggregated metadata.

However, we may update the certs anyway.
