### ISSUE TITLE
Relay state response

### ISSUE THREAD

**Issue by demesg** [swedenconnect/swedish-eid-idp#70]
Not sure if this is a bug or an issue with our enviroment settings, but in the SAML request the relay state is 'MA==' (base64 of 0)
But in the response is XML encoded to: `MA&#x3d;&#x3d`. Proper URL encoding should be : 'MA%3D%3D'
This makes our SP behave strangely and can not URL decode. Any idea how to make Shibb encode url in propper way or turn off xml encodning in response?

**Comment by martin-lindstrom** [comment]
Sorry for the delay. 

We are abandoning Shibboleth for our own IdP base, so it would be better if you asked this question in Shib mailing lists.
